name: CI -  Integrações Continuas

on: 
  pull_request:
    branches: ["main"]

jobs:
  integracoes-continuas:
    runs-on: ubuntu-latest

    steps:
    # 1. Baixa o código
    - name: Checkout do código 
      uses: actions/checkout@v3
    
    # 2. Configura o Node.js
    - name: Usando Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 22. #Se Docker, tem que ser a mesma versão

    # 3. Instala as Dependências
    # 4. Compila o TypeScript
    # Nosso primeiro teste: O código compila?
    # testes (jest):
    - name: Instalar, compilar e testar
      run: |
        npm install
        npm run build
        npm run test