name: CI -  Integrações Continuas

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  integracoes-continuas:
    runs-on: ubuntu-latest

    steps:
    # 1. Baixa o código
    - name: Checkout do código 
      uses: actions/checkout@v4
    
    # 2. Configura o Node.js
    - name: Usando Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22" #Se Docker, tem que ser a mesma versão

    # 3, 4 e 6. Instala npm, Compila tsc e Testa
    - name: Instalar, compilar e testar
      run: |
        npm install
        npm run build
        npm run test
